DEBUG = False

CONTROLLER_HOST = "127.0.0.1"
ELEVATOR_HOST = CONTROLLER_HOST
CONTROLLER_PORT = 8000
ELEVATOR_PORT = CONTROLLER_PORT + 1

REDIS = dict(
    USERNAME="default",
    PASSWORD="",
    HOST="",
    PORT=0,
)