DEBUG = False
CONF_ENV_VAR_NAME = "ELEVATOR_SETTINGS"

CONTROLLER_HOST = "127.0.0.1"
ELEVATOR_HOST = CONTROLLER_HOST
CONTROLLER_PORT = 8000
# TODO: implement ELEVATOR_PORT_RANGE

REDIS = dict(USERNAME="", PASSWORD="", HOST="127.0.0.1", PORT=6379,)
